In [1]:
from numpy import *

In [2]:
m = random.rand(4, 4)

In [3]:
m

array([[0.46317124, 0.99255862, 0.15695317, 0.54009467],
       [0.51074016, 0.81021309, 0.48215969, 0.18517648],
       [0.35379922, 0.35891819, 0.40296743, 0.5772505 ],
       [0.2041329 , 0.52763391, 0.57096998, 0.1819333 ]])

In [4]:
m = eye(4)

In [5]:
m.shape

(4, 4)

In [6]:
m = random.rand(4)

In [7]:
m

array([0.53299487, 0.03672243, 0.57687256, 0.3797909 ])

In [8]:
m.argsort?

Docstring:
a.argsort(axis=-1, kind=None, order=None)

Returns the indices that would sort this array.

Refer to `numpy.argsort` for full documentation.

See Also
--------
numpy.argsort : equivalent function
Type:      builtin_function_or_method


In [9]:
m.argsort()

array([1, 3, 0, 2])

In [10]:
tile?

Signature: tile(A, reps)
Docstring:
Construct an array by repeating A the number of times given by reps.

If `reps` has length ``d``, the result will have dimension of
``max(d, A.ndim)``.

If ``A.ndim < d``, `A` is promoted to be d-dimensional by prepending new
axes. So a shape (3,) array is promoted to (1, 3) for 2-D replication,
or shape (1, 1, 3) for 3-D replication. If this is not the desired
behavior, promote `A` to d-dimensions manually before calling this
function.

If ``A.ndim > d``, `reps` is promoted to `A`.ndim by pre-pending 1's to it.
Thus for an `A` of shape (2, 3, 4, 5), a `reps` of (2, 2) is treated as
(1, 1, 2, 2).

Note : Although tile may be used for broadcasting, it is strongly
recommended to use numpy's broadcasting operations and functions.

Parameters
----------
A : array_like
    The input array.
reps : array_like
    The number of repetitions of `A` along each axis.

Returns
-------
c : ndarray
    The tiled output array.

See Also
--------
repeat : Repeat elem

In [11]:
tile(array([0, 1, 2]), (2, 1))

array([[0, 1, 2],
       [0, 1, 2]])